---
- name: Uninstall OpenJDk
  become: yes
  apt:
    name: "openjdk-*"
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes

- name: Cleaning up
  become: yes
  shell: apt purge --autoremove jdk-*
