---
- name: Validate Installation
  command: dpkg-query -l "{{ jdk_name }}"
  register: package_check

- name: Message
  debug: 
    msg: "Package found"
  when: package_check is succeeded
  failed_when: package_check.rc == 1
