---
- name: Checking Java installation
  shell: javac -version
  register: javac_output
  ignore_errors: true
  
- shell: javac -version | awk -F '[ .]' '{print $2}'
  register: javac_v
  when: javac_output.rc == 0

- name: Check Java Version
  set_fact:
    javac_version: "{{ javac_v.stdout | int }}"
  when: javac_output.rc == 0 and javac_v.stdout | int != 1

- shell: javac -version | awk -F '[ .]' '{print $3}'
  register: javac_third_version
  when: javac_output.rc == 0 and javac_v.stdout == "1"

- name: Check Java Version
  set_fact:
    javac_version: "{{ javac_third_version.stdout | int }}"
  when: javac_output.rc == 0 and javac_v.stdout == "1"

- name: Checking Required OpenJDK Version
  set_fact:
    openjdk_version: "{{ openjdk_version | int }}"

- name: Uninstall existing OpenJDk package
  become: yes
  apt:
    name: "openjdk-*"
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes
  when: javac_output.rc == 0 and javac_version != openjdk_version
  
- name: Uninstall existing OpenJDK package
  become: yes
  shell: |
    sed -i '/JAVA_HOME/d' /etc/bash.bashrc
    rm -rf /opt/jdk-*
    rm -rf /opt/java-se-*
  when: javac_output.rc == 0 and javac_version != openjdk_version

- name: Installing Openjdk using apt
  apt:
    name: "openjdk-{{ openjdk_version }}-jdk-headless"
    state: present
  become: yes
  when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and (openjdk_version == "8" or openjdk_version == "11" or openjdk_version == "21" or (openjdk_version | int > 16 and openjdk_version | int < 20))

- name: Preparing Java version
  become: yes
  block:
    - name: Preparing Java 14/15/16/20
      set_fact:
        j_var: 36
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and ((openjdk_version | int > 13 and openjdk_version | int < 17) or openjdk_version == "20")

    - name: Preparing Java 12 Download URL
      set_fact:
        j_var: 32
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and openjdk_version == "12"

    - name: Preparing Java 13 Download URL
      set_fact:
        j_var: 33
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and openjdk_version == "13"

- name: Setup Java Download url
  become: yes
  block:
    - name: Setup Java 12/13/14/15/16/20 Download URL
      set_fact:
        url: https://download.java.net/openjdk/jdk{{ openjdk_version }}/ri/openjdk-{{ openjdk_version }}+{{ j_var }}_linux-x64_bin.tar.gz
        gz_file: openjdk-{{ openjdk_version }}+{{ j_var }}_linux-x64_bin.tar.gz
        java_file: jdk-{{ openjdk_version }}
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and ((openjdk_version | int > 11 and openjdk_version | int < 17) or openjdk_version == "20")

    - name: Setup Java 7 Download URL
      set_fact:
        url: https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
        gz_file: openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
        java_file: java-se-7u75-ri
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and openjdk_version == "7"

    - name: Setup Java 10 Download URL
      set_fact:
        url: https://download.java.net/openjdk/jdk10/ri/openjdk-10+44_linux-x64_bin_ri.tar.gz
        gz_file: openjdk-10+44_linux-x64_bin_ri.tar.gz
        java_file: jdk-{{ openjdk_version }}
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and openjdk_version == "10"

- name: Installing Java
  become: yes
  block:
    - name: Installing java 9
      shell: |
        wget -P /tmp/ https://download.java.net/openjdk/jdk9/ri/openjdk-9+181_linux-x64_ri.zip
        unzip /tmp/openjdk-9+181_linux-x64_ri.zip -d /opt/
        rm /tmp/openjdk-* 
        echo 'export JAVA_HOME=/opt/java-se-9-ri/jdk-9' >> /etc/bash.bashrc
        echo 'export PATH=$PATH:$JAVA_HOME/bin' >> /etc/bash.bashrc
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and openjdk_version == "9"

    - name: Installing Java 12/13/14/15/16/20
      shell: |
        wget -P /tmp/ {{ url }}
        tar -xf /tmp/{{ gz_file }} -C /opt/
        rm /tmp/openjdk-* 
        echo 'export JAVA_HOME=/opt/{{ java_file }}' >> /etc/bash.bashrc
        echo 'export PATH=$PATH:$JAVA_HOME/bin' >> /etc/bash.bashrc
      when: (javac_output.rc != 0 or (javac_output.rc == 0 and javac_version != openjdk_version)) and ((openjdk_version | int > 11 and openjdk_version | int < 17) or openjdk_version == "20" or openjdk_version == "10" or openjdk_version == "7")
