---
- name: Uninstall existing OpenJDk package
  become: yes
  apt:
    name: "openjdk-*"
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes

- name: Uninstall existing OpenJDK package
  become: yes
  shell: |
    sed -i '/JAVA_HOME/d' /etc/bash.bashrc
    rm -rf /opt/jdk-*
    rm -rf /opt/java-se-*



