---
- name: Removing package
  ansible.builtin.include_tasks: oah-remove.yml



- name: Getting default conf.
  become: yes
  ansible.builtin.git:
    repo: 'https://github.com/asa1997/ansible-role-oah-java.git'
    dest: '{{ java_tmp }}'
    clone: yes

- name: Resetting default conf.
  ansible.builtin.copy:
    src: "{{ java_tmp }}/defaults/main.yml"
    dest: "{{ role_path }}/defaults/main.yml"
    remote_src: yes

- name: Cleaning up
  file:
    path: "{{ java_tmp }}"
    state: absent
  
- name: Installing package
  ansible.builtin.include_tasks: oah-install.yml
